// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/hookdeck-go/models/components"
	"net/http"
)

type AddCustomDomainRequest struct {
	AddCustomHostname components.AddCustomHostname `request:"mediaType=application/json"`
	TeamID            string                       `pathParam:"style=simple,explode=false,name=team_id"`
}

func (o *AddCustomDomainRequest) GetAddCustomHostname() components.AddCustomHostname {
	if o == nil {
		return components.AddCustomHostname{}
	}
	return o.AddCustomHostname
}

func (o *AddCustomDomainRequest) GetTeamID() string {
	if o == nil {
		return ""
	}
	return o.TeamID
}

type AddCustomDomainResponse struct {
	// Custom domain successfuly added
	AddCustomHostname *components.AddCustomHostname
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *AddCustomDomainResponse) GetAddCustomHostname() *components.AddCustomHostname {
	if o == nil {
		return nil
	}
	return o.AddCustomHostname
}

func (o *AddCustomDomainResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *AddCustomDomainResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *AddCustomDomainResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
