// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"errors"
	"github.com/speakeasy-sdks/hookdeck-go/internal/utils"
	"github.com/speakeasy-sdks/hookdeck-go/models/components"
	"net/http"
)

type ConfigsType string

const (
	ConfigsTypeIssueTriggerDeliveryConfigs       ConfigsType = "IssueTriggerDeliveryConfigs"
	ConfigsTypeIssueTriggerTransformationConfigs ConfigsType = "IssueTriggerTransformationConfigs"
	ConfigsTypeIssueTriggerBackpressureConfigs   ConfigsType = "IssueTriggerBackpressureConfigs"
)

type Configs struct {
	IssueTriggerDeliveryConfigs       *components.IssueTriggerDeliveryConfigs
	IssueTriggerTransformationConfigs *components.IssueTriggerTransformationConfigs
	IssueTriggerBackpressureConfigs   *components.IssueTriggerBackpressureConfigs

	Type ConfigsType
}

func CreateConfigsIssueTriggerDeliveryConfigs(issueTriggerDeliveryConfigs components.IssueTriggerDeliveryConfigs) Configs {
	typ := ConfigsTypeIssueTriggerDeliveryConfigs

	return Configs{
		IssueTriggerDeliveryConfigs: &issueTriggerDeliveryConfigs,
		Type:                        typ,
	}
}

func CreateConfigsIssueTriggerTransformationConfigs(issueTriggerTransformationConfigs components.IssueTriggerTransformationConfigs) Configs {
	typ := ConfigsTypeIssueTriggerTransformationConfigs

	return Configs{
		IssueTriggerTransformationConfigs: &issueTriggerTransformationConfigs,
		Type:                              typ,
	}
}

func CreateConfigsIssueTriggerBackpressureConfigs(issueTriggerBackpressureConfigs components.IssueTriggerBackpressureConfigs) Configs {
	typ := ConfigsTypeIssueTriggerBackpressureConfigs

	return Configs{
		IssueTriggerBackpressureConfigs: &issueTriggerBackpressureConfigs,
		Type:                            typ,
	}
}

func (u *Configs) UnmarshalJSON(data []byte) error {

	issueTriggerDeliveryConfigs := components.IssueTriggerDeliveryConfigs{}
	if err := utils.UnmarshalJSON(data, &issueTriggerDeliveryConfigs, "", true, true); err == nil {
		u.IssueTriggerDeliveryConfigs = &issueTriggerDeliveryConfigs
		u.Type = ConfigsTypeIssueTriggerDeliveryConfigs
		return nil
	}

	issueTriggerTransformationConfigs := components.IssueTriggerTransformationConfigs{}
	if err := utils.UnmarshalJSON(data, &issueTriggerTransformationConfigs, "", true, true); err == nil {
		u.IssueTriggerTransformationConfigs = &issueTriggerTransformationConfigs
		u.Type = ConfigsTypeIssueTriggerTransformationConfigs
		return nil
	}

	issueTriggerBackpressureConfigs := components.IssueTriggerBackpressureConfigs{}
	if err := utils.UnmarshalJSON(data, &issueTriggerBackpressureConfigs, "", true, true); err == nil {
		u.IssueTriggerBackpressureConfigs = &issueTriggerBackpressureConfigs
		u.Type = ConfigsTypeIssueTriggerBackpressureConfigs
		return nil
	}

	return errors.New("could not unmarshal into supported union types")
}

func (u Configs) MarshalJSON() ([]byte, error) {
	if u.IssueTriggerDeliveryConfigs != nil {
		return utils.MarshalJSON(u.IssueTriggerDeliveryConfigs, "", true)
	}

	if u.IssueTriggerTransformationConfigs != nil {
		return utils.MarshalJSON(u.IssueTriggerTransformationConfigs, "", true)
	}

	if u.IssueTriggerBackpressureConfigs != nil {
		return utils.MarshalJSON(u.IssueTriggerBackpressureConfigs, "", true)
	}

	return nil, errors.New("could not marshal union type: all fields are null")
}

type CreateIssueTriggerRequestBody struct {
	// Notification channels object for the specific channel type
	Channels *components.IssueTriggerChannels `json:"channels"`
	// Configuration object for the specific issue type selected
	Configs *Configs `json:"configs,omitempty"`
	// Optional unique name to use as reference when using the API
	Name *string `json:"name,omitempty"`
	// Issue type
	Type components.IssueType `json:"type"`
}

func (o *CreateIssueTriggerRequestBody) GetChannels() *components.IssueTriggerChannels {
	if o == nil {
		return nil
	}
	return o.Channels
}

func (o *CreateIssueTriggerRequestBody) GetConfigs() *Configs {
	if o == nil {
		return nil
	}
	return o.Configs
}

func (o *CreateIssueTriggerRequestBody) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *CreateIssueTriggerRequestBody) GetType() components.IssueType {
	if o == nil {
		return components.IssueType("")
	}
	return o.Type
}

type CreateIssueTriggerResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// A single issue trigger
	IssueTrigger *components.IssueTrigger
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *CreateIssueTriggerResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateIssueTriggerResponse) GetIssueTrigger() *components.IssueTrigger {
	if o == nil {
		return nil
	}
	return o.IssueTrigger
}

func (o *CreateIssueTriggerResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateIssueTriggerResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
