// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/hookdeck-go/models/components"
	"net/http"
)

type DeleteIntegrationRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *DeleteIntegrationRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type DeleteIntegrationResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// An object with deleted integration id
	DeletedIntegration *components.DeletedIntegration
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *DeleteIntegrationResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteIntegrationResponse) GetDeletedIntegration() *components.DeletedIntegration {
	if o == nil {
		return nil
	}
	return o.DeletedIntegration
}

func (o *DeleteIntegrationResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteIntegrationResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
