// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy-sdks/hookdeck-go/v2/models/components"
	"net/http"
)

// Target - Bookmark target
type Target string

const (
	TargetHTTP Target = "http"
	TargetCli  Target = "cli"
)

func (e Target) ToPointer() *Target {
	return &e
}

func (e *Target) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "http":
		fallthrough
	case "cli":
		*e = Target(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Target: %v", v)
	}
}

type TriggerBookmarkRequestBody struct {
	// Bookmark target
	Target *Target `json:"target,omitempty"`
}

func (o *TriggerBookmarkRequestBody) GetTarget() *Target {
	if o == nil {
		return nil
	}
	return o.Target
}

type TriggerBookmarkRequest struct {
	RequestBody TriggerBookmarkRequestBody `request:"mediaType=application/json"`
	ID          string                     `pathParam:"style=simple,explode=false,name=id"`
}

func (o *TriggerBookmarkRequest) GetRequestBody() TriggerBookmarkRequestBody {
	if o == nil {
		return TriggerBookmarkRequestBody{}
	}
	return o.RequestBody
}

func (o *TriggerBookmarkRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type TriggerBookmarkResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Array of created events
	EventArray []components.Event
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *TriggerBookmarkResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *TriggerBookmarkResponse) GetEventArray() []components.Event {
	if o == nil {
		return nil
	}
	return o.EventArray
}

func (o *TriggerBookmarkResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *TriggerBookmarkResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
