// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy-sdks/hookdeck-go/models/components"
	"net/http"
)

// RateLimitPeriod - Period to rate limit attempts
type RateLimitPeriod string

const (
	RateLimitPeriodSecond RateLimitPeriod = "second"
	RateLimitPeriodMinute RateLimitPeriod = "minute"
	RateLimitPeriodHour   RateLimitPeriod = "hour"
)

func (e RateLimitPeriod) ToPointer() *RateLimitPeriod {
	return &e
}

func (e *RateLimitPeriod) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "second":
		fallthrough
	case "minute":
		fallthrough
	case "hour":
		*e = RateLimitPeriod(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RateLimitPeriod: %v", v)
	}
}

// Destination input object
type Destination struct {
	// Config for the destination's auth method
	AuthMethod *components.DestinationAuthMethodConfig `json:"auth_method,omitempty"`
	// Path for the CLI destination
	CliPath *string `json:"cli_path,omitempty"`
	// HTTP method used on requests sent to the destination, overrides the method used on requests sent to the source.
	HTTPMethod *components.DestinationHTTPMethod `json:"http_method,omitempty"`
	// Name for the destination
	Name                   string `json:"name"`
	PathForwardingDisabled *bool  `json:"path_forwarding_disabled,omitempty"`
	// Limit event attempts to receive per period
	RateLimit *int64 `json:"rate_limit,omitempty"`
	// Period to rate limit attempts
	RateLimitPeriod *RateLimitPeriod `json:"rate_limit_period,omitempty"`
	// Endpoint of the destination
	URL *string `json:"url,omitempty"`
}

func (o *Destination) GetAuthMethod() *components.DestinationAuthMethodConfig {
	if o == nil {
		return nil
	}
	return o.AuthMethod
}

func (o *Destination) GetCliPath() *string {
	if o == nil {
		return nil
	}
	return o.CliPath
}

func (o *Destination) GetHTTPMethod() *components.DestinationHTTPMethod {
	if o == nil {
		return nil
	}
	return o.HTTPMethod
}

func (o *Destination) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Destination) GetPathForwardingDisabled() *bool {
	if o == nil {
		return nil
	}
	return o.PathForwardingDisabled
}

func (o *Destination) GetRateLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.RateLimit
}

func (o *Destination) GetRateLimitPeriod() *RateLimitPeriod {
	if o == nil {
		return nil
	}
	return o.RateLimitPeriod
}

func (o *Destination) GetURL() *string {
	if o == nil {
		return nil
	}
	return o.URL
}

// Ruleset input object
type Ruleset struct {
	IsTeamDefault *bool `json:"is_team_default,omitempty"`
	// Name for the ruleset
	Name string `json:"name"`
	// Array of rules to apply
	Rules []components.Rule `json:"rules,omitempty"`
}

func (o *Ruleset) GetIsTeamDefault() *bool {
	if o == nil {
		return nil
	}
	return o.IsTeamDefault
}

func (o *Ruleset) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Ruleset) GetRules() []components.Rule {
	if o == nil {
		return nil
	}
	return o.Rules
}

// Source input object
type Source struct {
	// List of allowed HTTP methods. Defaults to PUT, POST, PATCH, DELETE.
	AllowedHTTPMethods []components.SourceAllowedHTTPMethod `json:"allowed_http_methods,omitempty"`
	// Custom response object
	CustomResponse *components.SourceCustomResponse `json:"custom_response,omitempty"`
	// A unique name for the source
	Name string `json:"name"`
}

func (o *Source) GetAllowedHTTPMethods() []components.SourceAllowedHTTPMethod {
	if o == nil {
		return nil
	}
	return o.AllowedHTTPMethods
}

func (o *Source) GetCustomResponse() *components.SourceCustomResponse {
	if o == nil {
		return nil
	}
	return o.CustomResponse
}

func (o *Source) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

type UpsertConnectionRequestBody struct {
	// Destination input object
	Destination *Destination `json:"destination,omitempty"`
	// ID of a destination to bind to the connection
	DestinationID *string `json:"destination_id,omitempty"`
	// A unique name of the connection for the source
	Name string `json:"name"`
	// Array of rules to apply
	Rules []components.Rule `json:"rules,omitempty"`
	// Ruleset input object
	Ruleset *Ruleset `json:"ruleset,omitempty"`
	// ID of a rule to bind to the connection. Default to the Workspace default ruleset
	RulesetID *string `json:"ruleset_id,omitempty"`
	// Source input object
	Source *Source `json:"source,omitempty"`
	// ID of a source to bind to the connection
	SourceID *string `json:"source_id,omitempty"`
}

func (o *UpsertConnectionRequestBody) GetDestination() *Destination {
	if o == nil {
		return nil
	}
	return o.Destination
}

func (o *UpsertConnectionRequestBody) GetDestinationID() *string {
	if o == nil {
		return nil
	}
	return o.DestinationID
}

func (o *UpsertConnectionRequestBody) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *UpsertConnectionRequestBody) GetRules() []components.Rule {
	if o == nil {
		return nil
	}
	return o.Rules
}

func (o *UpsertConnectionRequestBody) GetRuleset() *Ruleset {
	if o == nil {
		return nil
	}
	return o.Ruleset
}

func (o *UpsertConnectionRequestBody) GetRulesetID() *string {
	if o == nil {
		return nil
	}
	return o.RulesetID
}

func (o *UpsertConnectionRequestBody) GetSource() *Source {
	if o == nil {
		return nil
	}
	return o.Source
}

func (o *UpsertConnectionRequestBody) GetSourceID() *string {
	if o == nil {
		return nil
	}
	return o.SourceID
}

type UpsertConnectionResponse struct {
	// A single connection
	Connection *components.Connection
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *UpsertConnectionResponse) GetConnection() *components.Connection {
	if o == nil {
		return nil
	}
	return o.Connection
}

func (o *UpsertConnectionResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpsertConnectionResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpsertConnectionResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
