// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

// DestinationAuthMethodSignatureConfig - Empty config for the destination's auth method
type DestinationAuthMethodSignatureConfig struct {
}
