// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"hookdeck-go/pkg/models/shared"
	"net/http"
)

type DeleteIssueTriggerRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

type DeleteIssueTriggerResponse struct {
	// Not Found
	APIErrorResponse *shared.APIErrorResponse
	ContentType      string
	// An object with deleted issue trigger's id
	DeletedIssueTriggerResponse *shared.DeletedIssueTriggerResponse
	StatusCode                  int
	RawResponse                 *http.Response
}
