// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/hookdeck-go/pkg/models/shared"
	"net/http"
)

type GetIssueRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetIssueRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type GetIssueResponse struct {
	ContentType string
	// A single issue
	IssueWithData *shared.IssueWithData
	StatusCode    int
	RawResponse   *http.Response
}

func (o *GetIssueResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetIssueResponse) GetIssueWithData() *shared.IssueWithData {
	if o == nil {
		return nil
	}
	return o.IssueWithData
}

func (o *GetIssueResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetIssueResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
