// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/hookdeck-go/pkg/models/shared"
	"github.com/speakeasy-sdks/hookdeck-go/pkg/utils"
	"net/http"
)

type UpdateBookmarkRequestBody struct {
	AdditionalProperties map[string]interface{} `additionalProperties:"true" json:"-"`
	// ID of the event data to bookmark
	EventDataID *string `json:"event_data_id,omitempty"`
	// Descriptive name of the bookmark
	Label *string `json:"label,omitempty"`
	// A unique, human-friendly name for the bookmark
	Name *string `json:"name,omitempty"`
	// ID of the associated connection
	WebhookID *string `json:"webhook_id,omitempty"`
}

func (u UpdateBookmarkRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateBookmarkRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *UpdateBookmarkRequestBody) GetAdditionalProperties() map[string]interface{} {
	if o == nil {
		return nil
	}
	return o.AdditionalProperties
}

func (o *UpdateBookmarkRequestBody) GetEventDataID() *string {
	if o == nil {
		return nil
	}
	return o.EventDataID
}

func (o *UpdateBookmarkRequestBody) GetLabel() *string {
	if o == nil {
		return nil
	}
	return o.Label
}

func (o *UpdateBookmarkRequestBody) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *UpdateBookmarkRequestBody) GetWebhookID() *string {
	if o == nil {
		return nil
	}
	return o.WebhookID
}

type UpdateBookmarkRequest struct {
	RequestBody UpdateBookmarkRequestBody `request:"mediaType=application/json"`
	ID          string                    `pathParam:"style=simple,explode=false,name=id"`
}

func (o *UpdateBookmarkRequest) GetRequestBody() UpdateBookmarkRequestBody {
	if o == nil {
		return UpdateBookmarkRequestBody{}
	}
	return o.RequestBody
}

func (o *UpdateBookmarkRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type UpdateBookmarkResponse struct {
	// A single bookmark
	Bookmark *shared.Bookmark
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *UpdateBookmarkResponse) GetBookmark() *shared.Bookmark {
	if o == nil {
		return nil
	}
	return o.Bookmark
}

func (o *UpdateBookmarkResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateBookmarkResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateBookmarkResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
