// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
)

type APIErrorResponseData struct {
}

// APIErrorResponse - Error response model
type APIErrorResponse struct {
	// Error code
	Code string                `json:"code"`
	Data *APIErrorResponseData `json:"data,omitempty"`
	// Error description
	Message string `json:"message"`
	// Status code
	Status float32 `json:"status"`
}

var _ error = &APIErrorResponse{}

func (e *APIErrorResponse) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
