// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// AttachedIntegrationToSource - Attach operation success status
type AttachedIntegrationToSource struct {
	Success bool `json:"success"`
}

func (o *AttachedIntegrationToSource) GetSuccess() bool {
	if o == nil {
		return false
	}
	return o.Success
}
