// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-sdks/hookdeck-go/pkg/utils"
)

type BatchOperationPaginatedResult struct {
	AdditionalProperties map[string]interface{} `additionalProperties:"true" json:"-"`
	Count                *int64                 `json:"count,omitempty"`
	Models               []BatchOperation       `json:"models,omitempty"`
	Pagination           *SeekPagination        `json:"pagination,omitempty"`
}

func (b BatchOperationPaginatedResult) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BatchOperationPaginatedResult) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *BatchOperationPaginatedResult) GetAdditionalProperties() map[string]interface{} {
	if o == nil {
		return nil
	}
	return o.AdditionalProperties
}

func (o *BatchOperationPaginatedResult) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *BatchOperationPaginatedResult) GetModels() []BatchOperation {
	if o == nil {
		return nil
	}
	return o.Models
}

func (o *BatchOperationPaginatedResult) GetPagination() *SeekPagination {
	if o == nil {
		return nil
	}
	return o.Pagination
}
