// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-sdks/hookdeck-go/pkg/utils"
)

// BearerToken - Bearer Token
type BearerToken struct {
	// Bearer token config for the destination's auth method
	Config *DestinationAuthMethodBearerTokenConfig `json:"config,omitempty"`
	// Type of auth method
	type_ string `const:"BEARER_TOKEN" json:"type"`
}

func (b BearerToken) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BearerToken) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, true); err != nil {
		return err
	}
	return nil
}

func (o *BearerToken) GetConfig() *DestinationAuthMethodBearerTokenConfig {
	if o == nil {
		return nil
	}
	return o.Config
}

func (o *BearerToken) GetType() string {
	return "BEARER_TOKEN"
}
