// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy-sdks/hookdeck-go/pkg/utils"
)

type ConsoleLineType string

const (
	ConsoleLineTypeError ConsoleLineType = "error"
	ConsoleLineTypeLog   ConsoleLineType = "log"
	ConsoleLineTypeWarn  ConsoleLineType = "warn"
	ConsoleLineTypeInfo  ConsoleLineType = "info"
	ConsoleLineTypeDebug ConsoleLineType = "debug"
)

func (e ConsoleLineType) ToPointer() *ConsoleLineType {
	return &e
}

func (e *ConsoleLineType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "error":
		fallthrough
	case "log":
		fallthrough
	case "warn":
		fallthrough
	case "info":
		fallthrough
	case "debug":
		*e = ConsoleLineType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ConsoleLineType: %v", v)
	}
}

type ConsoleLine struct {
	AdditionalProperties map[string]interface{} `additionalProperties:"true" json:"-"`
	Message              string                 `json:"message"`
	Type                 ConsoleLineType        `json:"type"`
}

func (c ConsoleLine) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ConsoleLine) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ConsoleLine) GetAdditionalProperties() map[string]interface{} {
	if o == nil {
		return nil
	}
	return o.AdditionalProperties
}

func (o *ConsoleLine) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

func (o *ConsoleLine) GetType() ConsoleLineType {
	if o == nil {
		return ConsoleLineType("")
	}
	return o.Type
}
