// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-sdks/hookdeck-go/pkg/utils"
)

type DelayRule struct {
	// Delay to introduce in MS
	Delay int64 `json:"delay"`
	// A delay rule must be of type `delay`
	type_ string `const:"delay" json:"type"`
}

func (d DelayRule) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DelayRule) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, true); err != nil {
		return err
	}
	return nil
}

func (o *DelayRule) GetDelay() int64 {
	if o == nil {
		return 0
	}
	return o.Delay
}

func (o *DelayRule) GetType() string {
	return "delay"
}
