// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// DeletedIssueTriggerResponse - An object with deleted issue trigger's id
type DeletedIssueTriggerResponse struct {
	ID string `json:"id"`
}

func (o *DeletedIssueTriggerResponse) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}
