// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"errors"
	"github.com/speakeasy-sdks/hookdeck-go/pkg/utils"
)

type IssueWithDataType string

const (
	IssueWithDataTypeDeliveryIssueWithData       IssueWithDataType = "DeliveryIssueWithData"
	IssueWithDataTypeTransformationIssueWithData IssueWithDataType = "TransformationIssueWithData"
)

type IssueWithData struct {
	DeliveryIssueWithData       *DeliveryIssueWithData
	TransformationIssueWithData *TransformationIssueWithData

	Type IssueWithDataType
}

func CreateIssueWithDataDeliveryIssueWithData(deliveryIssueWithData DeliveryIssueWithData) IssueWithData {
	typ := IssueWithDataTypeDeliveryIssueWithData

	return IssueWithData{
		DeliveryIssueWithData: &deliveryIssueWithData,
		Type:                  typ,
	}
}

func CreateIssueWithDataTransformationIssueWithData(transformationIssueWithData TransformationIssueWithData) IssueWithData {
	typ := IssueWithDataTypeTransformationIssueWithData

	return IssueWithData{
		TransformationIssueWithData: &transformationIssueWithData,
		Type:                        typ,
	}
}

func (u *IssueWithData) UnmarshalJSON(data []byte) error {

	deliveryIssueWithData := DeliveryIssueWithData{}
	if err := utils.UnmarshalJSON(data, &deliveryIssueWithData, "", true, true); err == nil {
		u.DeliveryIssueWithData = &deliveryIssueWithData
		u.Type = IssueWithDataTypeDeliveryIssueWithData
		return nil
	}

	transformationIssueWithData := TransformationIssueWithData{}
	if err := utils.UnmarshalJSON(data, &transformationIssueWithData, "", true, true); err == nil {
		u.TransformationIssueWithData = &transformationIssueWithData
		u.Type = IssueWithDataTypeTransformationIssueWithData
		return nil
	}

	return errors.New("could not unmarshal into supported union types")
}

func (u IssueWithData) MarshalJSON() ([]byte, error) {
	if u.DeliveryIssueWithData != nil {
		return utils.MarshalJSON(u.DeliveryIssueWithData, "", true)
	}

	if u.TransformationIssueWithData != nil {
		return utils.MarshalJSON(u.TransformationIssueWithData, "", true)
	}

	return nil, errors.New("could not marshal union type: all fields are null")
}
