// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"errors"
	"github.com/speakeasy-sdks/hookdeck-go/pkg/utils"
)

type OrderByDirectionType string

const ()

type OrderByDirection struct {
	Type OrderByDirectionType
}

func (u *OrderByDirection) UnmarshalJSON(data []byte) error {

	return errors.New("could not unmarshal into supported union types")
}

func (u OrderByDirection) MarshalJSON() ([]byte, error) {

	return nil, errors.New("could not marshal union type: all fields are null")
}
