// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-sdks/hookdeck-go/pkg/utils"
)

type RetriedEvent struct {
	AdditionalProperties map[string]interface{} `additionalProperties:"true" json:"-"`
	Attempt              *EventAttempt          `json:"attempt"`
	Event                Event                  `json:"event"`
}

func (r RetriedEvent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RetriedEvent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *RetriedEvent) GetAdditionalProperties() map[string]interface{} {
	if o == nil {
		return nil
	}
	return o.AdditionalProperties
}

func (o *RetriedEvent) GetAttempt() *EventAttempt {
	if o == nil {
		return nil
	}
	return o.Attempt
}

func (o *RetriedEvent) GetEvent() Event {
	if o == nil {
		return Event{}
	}
	return o.Event
}
